#!/usr/bin/env python3
"""
Convert BFCL training data (pickle format) to SFT training format (parquet).

This script transforms the BFCL training data generated by generate_bfcl_training_data.py
into a format suitable for supervised fine-tuning (SFT).

The output format is designed to be compatible with verl's RL training format,
so that:
1. SFT and RL use the same tokenizer.apply_chat_template(messages, tools=...) approach
2. The model sees consistent input format during both SFT and RL stages
3. Models can be evaluated with litellm or similar tools using the same format

Input format (BFCL pickle):
{
    'query': str,
    'workflow_id': str,
    'workflow_pattern': List[str],
    'steps': List[{
        'step': int,
        'ground_truth': {'function': str, 'arguments': dict},
        'candidate_tools': List[str],
        'depends_on': List[int],
        'execution_result': dict
    }],
    'overall_success': bool,
    'metadata': dict
}

Output format (SFT parquet):
{
    'messages': List[Dict],     # Conversation messages (system, user, assistant, tool)
    'tools': List[Dict],        # Tool schemas in OpenAI format (applied via chat template)
    'workflow_id': str,
    'workflow_pattern': List[str],
    'num_steps': int,
    'overall_success': bool
}

The messages follow multi-turn tool calling pattern:
1. System message (simple, without tool definitions - tools injected via chat template)
2. User query
3. Assistant tool call (using model's native tool calling format)
4. Tool response
5. (Repeat 3-4 for each step)
6. Final assistant response summarizing results
"""

import argparse
import pickle
import json
import pandas as pd
from pathlib import Path
from typing import List, Dict, Any


def convert_parameters_to_json_schema(params: Dict[str, Any]) -> Dict[str, Any]:
    """
    Convert BFCL parameter format to standard JSON Schema format.

    BFCL uses "type": "dict" but JSON Schema requires "type": "object".
    """
    result = {}
    for key, value in params.items():
        if key == 'type' and value == 'dict':
            result['type'] = 'object'
        elif isinstance(value, dict):
            result[key] = convert_parameters_to_json_schema(value)
        elif isinstance(value, list):
            result[key] = [convert_parameters_to_json_schema(item) if isinstance(item, dict) else item for item in value]
        else:
            result[key] = value
    return result


def load_tool_schemas(tool_schema_path: str) -> Dict[str, Any]:
    """Load BookingAPI tool schemas from JSONL format."""
    tool_map = {}

    with open(tool_schema_path, 'r') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue

            schema = json.loads(line)
            func_name = schema['name']

            # Convert parameters to standard JSON Schema format
            # BFCL uses "type": "dict" but JSON Schema requires "type": "object"
            parameters = convert_parameters_to_json_schema(schema['parameters'])

            # Convert to OpenAI function format (compatible with chat template)
            tool_map[func_name] = {
                'type': 'function',
                'function': {
                    'name': schema['name'],
                    'description': schema['description'],
                    'parameters': parameters
                }
            }

    return tool_map


def create_system_prompt() -> str:
    """
    Create a simple system prompt WITHOUT tool definitions.

    Tools are injected via tokenizer.apply_chat_template(messages, tools=...)
    This matches the RL training format in verl.
    """
    return """You are a helpful assistant with access to booking.com APIs. You can help users search for hotels, flights, attractions, and more.

When you need to use a tool, output your tool call in this format:
<tool_call>
{
  "name": "function_name",
  "arguments": {
    "arg1": "value1",
    "arg2": "value2"
  }
}
</tool_call>

After you make a tool call, you will receive a response in this format:
<tool_response>
{
  "result": "..."
}
</tool_response>

You may need to make multiple tool calls to complete a task. After gathering all necessary information, provide a helpful summary to the user."""


def format_tool_call(function_name: str, arguments: Dict[str, Any]) -> str:
    """Format a tool call in the expected format."""
    return f"""<tool_call>
{json.dumps({"name": function_name, "arguments": arguments}, indent=2)}
</tool_call>"""


def format_tool_response(execution_result: Dict[str, Any]) -> str:
    """Format a tool response."""
    # Extract the actual result data
    if 'execution_result' in execution_result:
        result_data = execution_result['execution_result']
    else:
        result_data = execution_result

    return f"""<tool_response>
{json.dumps(result_data, indent=2)}
</tool_response>"""


def generate_final_response(sample: Dict[str, Any]) -> str:
    """Generate a final assistant response summarizing the results."""
    steps = sample['steps']

    # Build a summary based on the workflow and results
    summary_parts = []

    for i, step in enumerate(steps):
        exec_result = step.get('execution_result', {})
        func_name = step['ground_truth']['function']

        inner_result = exec_result.get('execution_result', {})
        # Handle case where inner_result might be a list or dict
        if isinstance(inner_result, list):
            # Some APIs return list directly
            result_data = inner_result
            status = True if result_data else False
        elif isinstance(inner_result, dict):
            status = inner_result.get('status', False)
            result_data = inner_result.get('data', {})
        else:
            status = False
            result_data = {}

        if status:
            # Handle case where result_data is a list
            if isinstance(result_data, list):
                if result_data:
                    first_item = result_data[0]
                    if isinstance(first_item, dict):
                        if 'name' in first_item:
                            summary_parts.append(f"Found: {first_item.get('name', 'Unknown')}")
                        elif 'formatted_address' in first_item:
                            summary_parts.append(f"Found location: {first_item.get('formatted_address', 'Unknown')}")
                        else:
                            summary_parts.append(f"Found {len(result_data)} results for {func_name}")
                    else:
                        summary_parts.append(f"Found {len(result_data)} results for {func_name}")
                continue

            # Generate step-specific summary for dict results
            if 'destinations' in result_data:
                destinations = result_data['destinations']
                if destinations:
                    dest = destinations[0]
                    summary_parts.append(f"Found location: {dest.get('cityName', 'Unknown')}, {dest.get('country', 'Unknown')}")

            elif 'products' in result_data:
                products = result_data['products']
                if products:
                    count = len(products)
                    summary_parts.append(f"Found {count} attractions/products")
                    # List first few
                    for p in products[:3]:
                        name = p.get('name', 'Unknown')
                        summary_parts.append(f"  - {name}")

            elif 'hotels' in result_data:
                hotels = result_data['hotels']
                if hotels:
                    count = len(hotels)
                    summary_parts.append(f"Found {count} hotels")
                    for h in hotels[:3]:
                        name = h.get('property', {}).get('name', 'Unknown')
                        summary_parts.append(f"  - {name}")

            elif 'data' in result_data and isinstance(result_data['data'], list):
                # Generic list result
                items = result_data['data']
                summary_parts.append(f"Found {len(items)} results for {func_name}")

            else:
                # Generic success
                summary_parts.append(f"Successfully completed {func_name}")

    if summary_parts:
        return "Based on my search, here's what I found:\n\n" + "\n".join(summary_parts)
    else:
        return "I've completed the requested searches. Please let me know if you need any additional information."


def convert_bfcl_sample_to_sft_format(
    sample: Dict[str, Any],
    tool_map: Dict[str, Any]
) -> Dict[str, Any]:
    """
    Convert a single BFCL sample to SFT training format.

    The format matches verl's RL training format:
    - messages: [system, user, assistant, tool, assistant, tool, ..., assistant]
    - tools: List of tool schemas (applied via tokenizer.apply_chat_template)

    Args:
        sample: BFCL training sample
        tool_map: Mapping from function name to schema

    Returns:
        Sample in SFT format with full conversation
    """
    # Collect candidate tools for this conversation
    all_candidate_tools = set()
    for step in sample['steps']:
        all_candidate_tools.update(step['candidate_tools'])

    # Get tool schemas in OpenAI format
    tools = [tool_map[name] for name in sorted(all_candidate_tools) if name in tool_map]

    messages = []

    # 1. System message (simple, without tool definitions)
    system_content = create_system_prompt()
    messages.append({
        "role": "system",
        "content": system_content
    })

    # 2. User query
    messages.append({
        "role": "user",
        "content": sample['query']
    })

    # 3. Process each step: assistant tool call -> tool response
    for step in sample['steps']:
        gt = step['ground_truth']
        exec_result = step.get('execution_result', {})

        # Assistant makes a tool call
        tool_call_text = format_tool_call(gt['function'], gt['arguments'])
        messages.append({
            "role": "assistant",
            "content": tool_call_text
        })

        # Tool response
        if exec_result:
            tool_response_text = format_tool_response(exec_result)
            messages.append({
                "role": "tool",
                "content": tool_response_text
            })

    result = {
        'messages': messages,
        'tools': tools,
        'num_steps': len(sample['steps'])
    }

    return result


def main():
    parser = argparse.ArgumentParser(
        description='Convert BFCL training data to SFT format'
    )
    parser.add_argument(
        '--input',
        type=str,
        required=True,
        help='Path to input BFCL pickle file (e.g., data/bfcl_training_3_per_workflow.pkl)'
    )
    parser.add_argument(
        '--output',
        type=str,
        required=True,
        help='Path to output parquet file (e.g., data/bfcl_sft_training.parquet)'
    )
    parser.add_argument(
        '--output-jsonl',
        type=str,
        default=None,
        help='Optional: Also output as JSONL file for easier inspection'
    )
    parser.add_argument(
        '--tool-schema-path',
        type=str,
        default='BFCL/bfcl_eval/data/multi_turn_func_doc/booking_api.json',
        help='Path to BookingAPI tool schemas'
    )
    parser.add_argument(
        '--filter-success',
        action='store_true',
        help='Only include samples with overall_success=True'
    )

    args = parser.parse_args()

    # Validate paths
    input_path = Path(args.input)
    if not input_path.exists():
        raise FileNotFoundError(f"Input file not found: {input_path}")

    tool_schema_path = Path(args.tool_schema_path)
    if not tool_schema_path.exists():
        raise FileNotFoundError(f"Tool schema file not found: {tool_schema_path}")

    # Load data
    print(f"Loading BFCL data from {input_path}...")
    with open(input_path, 'rb') as f:
        bfcl_data = pickle.load(f)

    print(f"Loaded {len(bfcl_data)} samples")

    # Filter if requested
    if args.filter_success:
        original_count = len(bfcl_data)
        bfcl_data = [s for s in bfcl_data if s.get('overall_success', False)]
        print(f"Filtered to {len(bfcl_data)} successful samples (removed {original_count - len(bfcl_data)})")

    # Load tool schemas
    print(f"Loading tool schemas from {tool_schema_path}...")
    tool_map = load_tool_schemas(tool_schema_path)
    print(f"Loaded {len(tool_map)} tool schemas")

    # Convert samples
    print("Converting samples to SFT format...")
    sft_samples = []
    for i, sample in enumerate(bfcl_data):
        try:
            sft_sample = convert_bfcl_sample_to_sft_format(sample, tool_map)
            sft_samples.append(sft_sample)
        except Exception as e:
            print(f"Warning: Failed to convert sample {i}: {e}")
            continue

    print(f"Successfully converted {len(sft_samples)} samples")

    # Compute stats
    avg_steps = sum(s['num_steps'] for s in sft_samples) / len(sft_samples)
    avg_messages = sum(len(s['messages']) for s in sft_samples) / len(sft_samples)
    avg_tools = sum(len(s['tools']) for s in sft_samples) / len(sft_samples)

    # Ensure output directory exists
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Save to parquet - store as native Python objects, not JSON strings
    # MultiTurnSFTDataset expects lists/dicts, not serialized JSON
    print(f"Saving to {args.output}...")
    parquet_samples = []
    for sample in sft_samples:
        parquet_samples.append({
            'messages': sample['messages'],  # List of dicts
            'tools': sample['tools'],        # List of dicts
            'num_steps': sample['num_steps']
        })

    df = pd.DataFrame(parquet_samples)
    df.to_parquet(args.output, engine='pyarrow', index=False)

    print(f"✓ Successfully saved {len(sft_samples)} samples to {args.output}")

    # Optionally save as JSONL for easier inspection
    if args.output_jsonl:
        jsonl_path = Path(args.output_jsonl)
        jsonl_path.parent.mkdir(parents=True, exist_ok=True)

        with open(jsonl_path, 'w') as f:
            for sample in sft_samples:
                f.write(json.dumps(sample, ensure_ascii=False) + '\n')

        print(f"✓ Also saved as JSONL to {args.output_jsonl}")

    print(f"\nDataset statistics:")
    print(f"  - Total samples: {len(sft_samples)}")
    print(f"  - Avg steps per sample: {avg_steps:.1f}")
    print(f"  - Avg messages per conversation: {avg_messages:.1f}")
    print(f"  - Avg candidate tools: {avg_tools:.1f}")

    # Show example
    if sft_samples:
        example = sft_samples[0]
        print(f"\nExample conversation structure:")
        print(f"  - Total messages: {len(example['messages'])}")
        print(f"  - Candidate tools: {len(example['tools'])} (applied via chat template)")
        for i, msg in enumerate(example['messages']):
            role = msg['role']
            content_preview = msg['content'][:80].replace('\n', ' ') + '...' if len(msg['content']) > 80 else msg['content'].replace('\n', ' ')
            print(f"    [{i}] {role}: {content_preview}")

    print(f"\nNote: Tools are stored separately and should be applied via:")
    print(f"  tokenizer.apply_chat_template(messages, tools=tools, add_generation_prompt=True)")


if __name__ == '__main__':
    main()
