#!/usr/bin/env python3
"""
Convert BFCL training data (pickle format) to verl RL training format (parquet).

This script transforms the BFCL training data generated by generate_bfcl_training_data.py
into the parquet format expected by verl's RL training pipeline.

Input format (BFCL pickle):
{
    'query': str,
    'workflow_id': str,
    'workflow_pattern': List[str],
    'steps': List[{
        'step': int,
        'ground_truth': {'function': str, 'arguments': dict},
        'candidate_tools': List[str],
        'depends_on': List[int],
        'execution_result': dict
    }],
    'overall_success': bool,
    'metadata': dict
}

Output format (verl parquet):
{
    'prompt': str,  # System prompt + user query
    'reward_model': List[List[dict]],  # Ground truth tool calls per step
    'candidate_tools': List[str],  # All valid tools for this query
    'extra_info': dict  # Step dependencies and metadata
}
"""

import argparse
import pickle
import json
import pandas as pd
from pathlib import Path
from typing import List, Dict, Any


def load_tool_schemas(tool_schema_path: str) -> Dict[str, Any]:
    """Load BookingAPI tool schemas from JSONL format."""
    tool_map = {}

    with open(tool_schema_path, 'r') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue

            schema = json.loads(line)
            func_name = schema['name']

            # Convert to OpenAI function format
            tool_map[func_name] = {
                'name': schema['name'],
                'description': schema['description'],
                'parameters': schema['parameters']
            }

    return tool_map


def create_system_prompt(tool_schemas: List[Dict[str, Any]]) -> str:
    """
    Create system prompt WITHOUT tool descriptions.

    Tool descriptions are automatically added by verl via the tokenizer's
    apply_chat_template(tools=...) parameter. Including them here causes
    duplication and wastes ~6,800 tokens per prompt.

    Args:
        tool_schemas: List of tool schemas (unused, kept for API compatibility)

    Returns:
        System prompt string without tool descriptions
    """
    prompt = """You are a helpful assistant with access to booking.com APIs. You can help users search for hotels, flights, attractions, and more.

When you need to use a tool, output your tool call in this format:
<tool_call>
{
  "name": "function_name",
  "arguments": {
    "arg1": "value1",
    "arg2": "value2"
  }
}
</tool_call>

After you make a tool call, you will receive a response in this format:
<tool_response>
{
  "result": "..."
}
</tool_response>"""

    # DO NOT include tool descriptions here - verl adds them automatically
    # via tokenizer.apply_chat_template(tools=tool_schemas)

    return prompt


def convert_bfcl_sample_to_rl_format(
    sample: Dict[str, Any],
    tool_map: Dict[str, Any]
) -> Dict[str, Any]:
    """
    Convert a single BFCL sample to verl RL training format.

    Args:
        sample: BFCL training sample
        tool_map: Mapping from function name to schema

    Returns:
        Sample in verl format
    """
    # Extract candidate tools across all steps
    all_candidate_tools = set()
    for step in sample['steps']:
        all_candidate_tools.update(step['candidate_tools'])

    # Get schemas for candidate tools
    candidate_tool_schemas = []
    for tool_name in sorted(all_candidate_tools):
        if tool_name in tool_map:
            candidate_tool_schemas.append(tool_map[tool_name])

    # Create system prompt
    system_prompt = create_system_prompt(candidate_tool_schemas)

    # Create full prompt (system + user query)
    prompt = f"{system_prompt}\n\nUser: {sample['query']}\n\nAssistant: "

    # Build reward model (ground truth per step)
    # Format: List[List[Dict[str, Any]]] where each step has candidate functions
    ground_truth_per_step = []
    execution_traces_per_step = []

    for step in sample['steps']:
        gt = step['ground_truth']

        # Each step has a list of candidate tools with success labels
        # For BFCL, only the ground truth function is marked as success=True
        step_candidates = []
        for tool_name in step['candidate_tools']:
            step_candidates.append({
                'name': tool_name,
                'success': tool_name == gt['function']
            })
        ground_truth_per_step.append(step_candidates)

        # Extract execution traces for R_atomic_validity
        # BFCL stores execution results for each step
        step_traces = {}
        exec_result = step.get('execution_result', {})

        if exec_result and exec_result.get('success', False):
            func_name = exec_result.get('function', gt['function'])
            step_traces[func_name] = {
                'success': True,
                'traces': [
                    {
                        'function_name': func_name,
                        'arguments': exec_result.get('arguments', gt.get('arguments', {})),
                        'result': exec_result.get('execution_result', {}),
                        'success': True
                    }
                ]
            }

        execution_traces_per_step.append(step_traces)

    reward_model = {
        'ground_truth': ground_truth_per_step,
        'execution_traces': execution_traces_per_step,  # NEW: for R_atomic_validity
        'style': 'tool_calling'
    }

    # Build step dependency info
    step_dependency = []
    for step in sample['steps']:
        deps = step.get('depends_on', [])
        step_dependency.append(deps if deps else None)

    # Create extra_info with metadata
    extra_info = {
        'step_dependency': step_dependency,
        'execution_traces': execution_traces_per_step,  # Required for R_atomic_validity
        'workflow_id': sample.get('workflow_id', ''),
        'workflow_pattern': sample.get('workflow_pattern', []),
        'num_steps': len(sample['steps']),
        'metadata': sample.get('metadata', {})
    }

    return {
        'data_source': 'bfcl',
        'agent_name': 'tool_agent',  # Must match registered agent loops
        'ability': 'tool_calling',
        'prompt': prompt,
        'reward_model': reward_model,
        'candidate_tools': sorted(list(all_candidate_tools)),
        'extra_info': extra_info
    }


def main():
    parser = argparse.ArgumentParser(
        description='Convert BFCL training data to verl RL format'
    )
    parser.add_argument(
        '--input',
        type=str,
        required=True,
        help='Path to input BFCL pickle file (e.g., data/bfcl_training_8.pkl)'
    )
    parser.add_argument(
        '--output',
        type=str,
        required=True,
        help='Path to output parquet file (e.g., data/bfcl_rl_training.parquet)'
    )
    parser.add_argument(
        '--tool-schema-path',
        type=str,
        default='environment/booking_api.json',
        help='Path to BookingAPI tool schemas'
    )
    parser.add_argument(
        '--filter-success',
        action='store_true',
        help='Only include samples with overall_success=True'
    )

    args = parser.parse_args()

    # Validate paths
    input_path = Path(args.input)
    if not input_path.exists():
        raise FileNotFoundError(f"Input file not found: {input_path}")

    tool_schema_path = Path(args.tool_schema_path)
    if not tool_schema_path.exists():
        raise FileNotFoundError(f"Tool schema file not found: {tool_schema_path}")

    # Load data
    print(f"Loading BFCL data from {input_path}...")
    with open(input_path, 'rb') as f:
        bfcl_data = pickle.load(f)

    print(f"Loaded {len(bfcl_data)} samples")

    # Filter if requested
    if args.filter_success:
        original_count = len(bfcl_data)
        bfcl_data = [s for s in bfcl_data if s.get('overall_success', False)]
        print(f"Filtered to {len(bfcl_data)} successful samples (removed {original_count - len(bfcl_data)})")

    # Load tool schemas
    print(f"Loading tool schemas from {tool_schema_path}...")
    tool_map = load_tool_schemas(tool_schema_path)
    print(f"Loaded {len(tool_map)} tool schemas")

    # Convert samples
    print("Converting samples to RL format...")
    rl_samples = []
    for i, sample in enumerate(bfcl_data):
        try:
            rl_sample = convert_bfcl_sample_to_rl_format(sample, tool_map)
            rl_samples.append(rl_sample)
        except Exception as e:
            print(f"Warning: Failed to convert sample {i}: {e}")
            continue

    print(f"Successfully converted {len(rl_samples)} samples")

    # Compute stats BEFORE serialization
    avg_steps = sum(len(s['reward_model']['ground_truth']) for s in rl_samples) / len(rl_samples)
    avg_tools = sum(len(s['candidate_tools']) for s in rl_samples) / len(rl_samples)

    # Save example structure before serialization
    example_prompt_len = 2  # Will be 2 messages (system + user)
    example_num_steps = len(rl_samples[0]['reward_model']['ground_truth']) if rl_samples else 0
    example_candidate_tools = len(rl_samples[0]['candidate_tools']) if rl_samples else 0
    example_first_step_tools = len(rl_samples[0]['reward_model']['ground_truth'][0]) if rl_samples and rl_samples[0]['reward_model']['ground_truth'] else 0

    # Convert to DataFrame and save with nested structures
    print(f"Saving to {args.output}...")

    # Ensure output directory exists
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Convert prompt from string to chat messages format and serialize complex structures
    for sample in rl_samples:
        # Split the prompt into system and user parts
        full_prompt = sample['prompt']

        # Extract system prompt and user query
        if "\n\nUser: " in full_prompt:
            system_part, user_part = full_prompt.split("\n\nUser: ", 1)
            if "\n\nAssistant: " in user_part:
                user_query = user_part.split("\n\nAssistant: ")[0]
            else:
                user_query = user_part
        else:
            # Fallback
            system_part = full_prompt
            user_query = ""

        # Convert to chat messages format
        sample['prompt'] = json.dumps([
            {"role": "system", "content": system_part},
            {"role": "user", "content": user_query}
        ])

        # Serialize complex nested structures to JSON strings for PyArrow compatibility
        sample['reward_model'] = json.dumps(sample['reward_model'])
        sample['extra_info'] = json.dumps(sample['extra_info'])
        sample['candidate_tools'] = json.dumps(sample['candidate_tools'])

    df = pd.DataFrame(rl_samples)
    df.to_parquet(args.output, engine='pyarrow', index=False)

    print(f"✓ Successfully saved {len(rl_samples)} samples to {args.output}")
    print(f"\nDataset statistics:")
    print(f"  - Total samples: {len(rl_samples)}")
    print(f"  - Avg steps per sample: {avg_steps:.1f}")
    print(f"  - Avg candidate tools: {avg_tools:.1f}")

    # Show example (using pre-serialization values)
    print(f"\nExample sample structure:")
    print(f"  - Prompt messages: {example_prompt_len}")
    print(f"  - Number of steps: {example_num_steps}")
    print(f"  - Candidate tools: {example_candidate_tools} tools")
    print(f"  - First step tools: {example_first_step_tools} candidates")


if __name__ == '__main__':
    main()
